### ISSUE TITLE
Broken Footer

### ISSUE THREAD

**Issue by ArmandoAmador** [nodebots/nodebots.nyc#2]
![screen shot 2015-12-31 at 7 19 41 pm](https://cloud.githubusercontent.com/assets/5686847/12069251/7c9fc3ea-aff3-11e5-9acd-da25ba230516.png)

**Comment by HipsterBrown** [comment]
Could you provide some more info, @ArmandoAmador?
- What browser were you viewing this in?
- Have you inspected the console?

**Comment by ArmandoAmador** [comment]
Not sure what Chrome version on my home mac, but on my work mac chrome `Version 47` this is how it looks.

![screen shot 2016-01-04 at 9 11 59 am](https://cloud.githubusercontent.com/assets/5686847/12091223/7f99a1ba-b2c3-11e5-8568-2c31d0d28771.png)

**Comment by ArmandoAmador** [comment]
Same deal with Firefox, I can try to investigate sometime this week, unless you get to it first @HipsterBrown 
![screen shot 2016-01-04 at 9 22 42 am](https://cloud.githubusercontent.com/assets/5686847/12091392/d1d6709c-b2c4-11e5-9a6d-acf30201e7a3.png)

**Comment by HipsterBrown** [comment]
Fixed by #5
